### ISSUE TITLE
Merge shake topology files using the add_molecules cli tool

### ISSUE THREAD

**Issue by ape33** [MolarVerse/PQAnalysis#82]
I tried to merge two topology files using the add_molecules tool using the command below and reveived an error:
`$ add_molecules mil68ga-md-01.rst <http://perylene-md-05.xyz|perylene-md-05.xyz> --topology-file <http://shake_mil.top|shake_mil.top> --added-topology-fi`
`le <http://shake_perylene.top|shake_perylene.top> --output-topology-file <http://shake.top|shake.top>`

`*WARNING:* PQAnalysis.AddMolecule` 
```         Extension of the topology file is only implemented for shake bonds. The extension of 
         general bonded topologies is not implemented yet. 
Traceback (most recent call last): 
 File "/home/ape/.conda/envs/pq/bin/add_molecules", line 8, in &lt;module&gt; 
   sys.exit(main()) 
            ^^^^^^ 
 File "/home/ape/.conda/envs/pq/lib/python3.12/site-packages/PQAnalysis/cli/add_molecules.py", line 26
3, in main 
   AddMoleculesCLI.run(args) 
 File "/home/ape/.conda/envs/pq/lib/python3.12/site-packages/PQAnalysis/cli/add_molecules.py", line 22
9, in run 
   add_molecule( 
 File "/home/ape/.conda/envs/pq/lib/python3.12/site-packages/decorator.py", line 232, in fun 
   return caller(func, *(extras + args), **kw) 
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
 File "/home/ape/.conda/envs/pq/lib/python3.12/site-packages/PQAnalysis/type_checking.py", line 113, i
n runtime_type_checking 
   return func(*args, **kwargs) 
          ^^^^^^^^^^^^^^^^^^^^^ 
 File "/home/ape/.conda/envs/pq/lib/python3.12/site-packages/PQAnalysis/tools/add_molecule.py", line 1
35, in add_molecule 
   _add_molecule.extend_topology_file( 
 File "/home/ape/.conda/envs/pq/lib/python3.12/site-packages/decorator.py", line 232, in fun 
   return caller(func, *(extras + args), **kw) 
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
 File "/home/ape/.conda/envs/pq/lib/python3.12/site-packages/PQAnalysis/type_checking.py", line 113, i
n runtime_type_checking 
   return func(*args, **kwargs) 
          ^^^^^^^^^^^^^^^^^^^^^ 
 File "/home/ape/.conda/envs/pq/lib/python3.12/site-packages/PQAnalysis/tools/add_molecule.py", line 3
96, in extend_topology_file 
   original_topology.extend_shake_bonds( 
 File "/home/ape/.conda/envs/pq/lib/python3.12/site-packages/decorator.py", line 232, in fun 
   return caller(func, *(extras + args), **kw) 
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
 File "/home/ape/.conda/envs/pq/lib/python3.12/site-packages/PQAnalysis/type_checking.py", line 113, i
n runtime_type_checking 
   return func(*args, **kwargs) 
          ^^^^^^^^^^^^^^^^^^^^^ 
 File "/home/ape/.conda/envs/pq/lib/python3.12/site-packages/PQAnalysis/topology/bonded_topology/bonde
d_topology.py", line 113, in extend_shake_bonds 
   max_index_shake_bonds = max( 
                           ^^^^ 
ValueError: max() iterable argument is empty```

[Slack Message](https://molarverse.slack.com/archives/C075KJ71LN4/p1717165249541809)

**Comment by 97gamjak** [comment]
closed with pr #85
